feat: Da eigen implementation docs & backup scripts
lambdaclass/zksync-era pull request #289
Opened 2024-09-30 21:11 UTC by juan518munoz

Docs on EigenDA integration, and scripts to bakcup and restore an ecosystem.

2024-10-02 14:46 UTC, gianbelinche requested changes
Also add the path fix for correct restoration

2024-10-02 14:46 UTC, gianbelinche commented on eigenda-integration.md
> +
This then needs a `./bin/zkt`

2024-10-04 20:38 UTC, gianbelinche approved these changes
LGTM

2024-10-07 16:04 UTC, juanbono approved these changes

2024-10-07 16:12 UTC, juan518munoz commented on eigenda-integration.md
> +          --l1-rpc-url https://ethereum-holesky-rpc.publicnode.com \
Good point! Applied this change to the eigenDA proxy step too, as it also made use of this variable.

2024-10-07 16:13 UTC, juanbono commented on eigenda-integration.md
> +          --l1-rpc-url https://ethereum-holesky-rpc.publicnode.com \
great!

2024-10-07 17:54 UTC, merged