Use `ETH_SENDER_SENDER_VALIDIUM_MODE` to check whether we need to cha…
lambdaclass/zksync-era pull request #32
Opened 2024-01-11 18:28 UTC by Oppen

…rge the pubdata

## What ❔

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.
- [ ] Spellcheck has been run via `cargo spellcheck --cfg=./spellcheck/era.cfg --code 1`.

2024-01-15 15:46 UTC, ilitteri approved these changes
LGTM

2024-01-15 18:47 UTC, mationorato requested changes
- please remove changes in older vms. we shoudl only modify vm_latests.
- Look at the comment about the submodule

2024-01-15 18:47 UTC, mationorato commented on .gitmodules
I think you want to point to 
url = https://github.com/lambdaclass/era-contracts.git
branch = validium_mode

2024-01-18 07:05 UTC, popzxc reviewed
I understand that this is a PoC phase, so please don't treat my comments as criticism of the existing solution; I understand that there will be some refactoring/rework before validium mode is added to the main codebase.

I just thought it may be helpful to elaborate on our expectations code-wise.

2024-01-18 07:05 UTC, popzxc commented on validium_mode_example/Context.sol
> +// SPDX-License-Identifier: MIT
Once we get closer to the mergeable solution, we'd expect the proper logical structure of the project (this applies to test code as well -- I assume this package will evolve to some form of integration test).

2024-01-18 14:19 UTC, ilitteri requested changes
Left some comments

2024-01-18 14:19 UTC, ilitteri commented on core/tests/ts-integration/src/diff_output.txt
Let's remove this file

2024-01-18 14:19 UTC, ilitteri commented on core/tests/ts-integration/src/diff_validium.txt
Let's remove this file

2024-01-18 14:19 UTC, ilitteri commented on core/tests/ts-integration/src/rollup_output.txt
Let's remove this file

2024-01-18 14:19 UTC, ilitteri commented on core/tests/ts-integration/src/validium_output.txt
Let's remove this file

2024-01-18 14:19 UTC, ilitteri commented on core/tests/ts-integration/src/validium_pubdata_0_output.txt
Let's remove this file

2024-01-18 14:19 UTC, ilitteri commented on core/lib/multivm/src/versions/vm_latest/oracles/storage.rs
Let's rollback this changes

2024-01-18 14:20 UTC, ilitteri commented on core/lib/multivm/src/versions/vm_latest/oracles/storage.rs
> +        println!("is initial");
Btw, we'll remove this rn cause is not useful anymore

2024-01-19 14:21 UTC, ilitteri approved these changes
LGTM, we still need to update the `era-contract` branch, but this will be another PR

2024-01-19 14:22 UTC, merged