feat(eigen-client-extra-features): Move inclusion logic
lambdaclass/zksync-era pull request #357
Opened 2024-11-25 18:02 UTC by gianbelinche

## What ❔
This PR moves inclusion and verify logic from disperse blob to get inclusion data

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zkstack dev fmt` and `zkstack dev lint`.

2024-11-25 21:28 UTC, juan518munoz reviewed
[Unused import: `DisperserBlobReply`](https://github.com/lambdaclass/zksync-era/pull/357/files#diff-50639b5d8317ac6c2332a1684199ec9498f9afa4cdb62d959c2e7e3dc733ecf7R25)

2024-11-26 19:15 UTC, juan518munoz approved these changes

2024-11-28 18:24 UTC, juanbono commented on core/node/da_clients/src/eigen/client.rs
> +    pub async fn get_commitment(&self, blob_id: &str) -> anyhow::Result<String> {
same here, anyhow should not be used

2024-11-28 18:24 UTC, juanbono commented on core/node/da_clients/src/eigen/sdk.rs
> +    pub async fn get_inclusion_data(&self, blob_id: &str) -> anyhow::Result<String> {
same here

2024-11-28 18:24 UTC, juanbono requested changes
Replace anyhow with thiserror

2024-11-28 18:37 UTC, juanbono approved these changes
Please move from anyhow to thiserror in another PR

2024-11-28 18:38 UTC, merged