feat(eigen-client-extra-features): address PR comments (part 4)
lambdaclass/zksync-era pull request #378
Opened 2024-12-18 20:11 UTC by gianbelinche

## What ❔
[`data_availability` full scan](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888687629)
[simpler ABI decoding](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888803680)
[infalible cast](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888781030)
[default disperser_rpc](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888672059)
[replace `String` with `Url`](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888718196)

## Why ❔

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zkstack dev fmt` and `zkstack dev lint`.

2024-12-18 20:49 UTC, juan518munoz requested changes

2024-12-18 20:49 UTC, juan518munoz commented on core/node/da_clients/src/eigen/verifier.rs
> +            .get(0)
clippy suggeestion:
```suggestion
            .first()
```

2024-12-18 20:49 UTC, juan518munoz commented on core/node/da_clients/src/eigen/verifier.rs
> +            .ok_or_else(|| "Incorrect result on contract call")?;
Another clippy suggestion:
```suggestion
            .ok_or("Incorrect result on contract call")?;
```

2024-12-18 20:49 UTC, juan518munoz commented on core/node/da_clients/src/eigen/verifier.rs
> +        //let url = Url::parse(&url).map_err(|_| VerificationError::LinkError)?;
Remove unused, commented code

2024-12-18 21:08 UTC, juan518munoz approved these changes

2024-12-19 15:46 UTC, gianbelinche commented on core/node/da_clients/src/eigen/verifier.rs
>      fn decode_bytes(&self, encoded: Vec<u8>) -> Result<Vec<u8>, String> {
Done!

2024-12-19 16:07 UTC, juanbono approved these changes

2024-12-19 16:07 UTC, merged